omitted_paths:
  - documentation/ServicePrincipal/*
  - "packages/@azure/arm-*"
  - "packages/@azure/cognitiveservices-*"
language: js
root_check_enabled: True
required_readme_sections:
  - "Azure .+ client library for JS"
  - ^Getting started$
  - ^Key concepts$
  - ^Examples$
  - ^Troubleshooting$
  - ^Next steps$
  - ^Contributing$
known_content_issues:
  - ['README.md', '#1583']
  - ['sdk/template/template/README.md', '#1583']
  - ['packages/@azure/applicationinsights-query/README.md', '#1583']
  - ['packages/@azure/batch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-autosuggest/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-computervision/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-contentmoderator/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-customimagesearch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-customsearch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-customvision-prediction/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-customvision-training/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-entitysearch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-face/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-imagesearch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-localsearch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-luis-authoring/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-luis-runtime/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-newssearch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-qnamaker/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-spellcheck/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-textanalytics/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-videosearch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-visualsearch/README.md', '#1583']
  - ['packages/@azure/cognitiveservices-websearch/README.md', '#1583']
  - ['packages/@azure/eventgrid/README.md', '#1583']
  - ['sdk/eventhubs/README.md', '#1583']
  - ['sdk/eventhubs/event-hubs/README.md', '#1583']
  - ['sdk/eventhubs/event-hubs/samples/README.md', '#1583']
  - ['sdk/eventhubs/event-processor-host/README.md', '#1583']
  - ['sdk/eventhubs/event-processor-host/samples/README.md', '#1583']
  - ['sdk/eventhubs/testhub/README.md', '#1583']
  - ['packages/@azure/graph/README.md', '#1583']
  - ['sdk/keyvault/keyvault/README.md', '#1583']
  - ['packages/@azure/loganalytics/README.md', '#1583']
  - ['sdk/servicebus/service-bus/README.md', '#1583']
  - ['sdk/servicebus/service-bus/samples/README.md', '#1583']
  - ['sdk/servicebus/service-bus/test/README.md', '#1583']
  - ['packages/@azure/servicefabric/README.md', '#1583']
  - ['sdk/storage/README.md', '#1583']
  - ['sdk/storage/storage-blob/README.md', '#1583']
  - ['sdk/storage/storage-blob/swagger/README.md', '#1583']
  - ['sdk/storage/storage-file/README.md', '#1583']
  - ['sdk/storage/storage-file/swagger/README.md', '#1583']
  - ['sdk/storage/storage-queue/README.md', '#1583']
  - ['sdk/storage/storage-queue/swagger/README.md', '#1583']
  - ['packages/@azure/storage-datalake/README.md', '#1583']
