omitted_paths:
  - documentation/ServicePrincipal/*
  - eng/tools/analyze-deps/**
  - eng/tools/select-packages/**
  - "sdk/*/arm-*"
  - "sdk/cognitiveservices/*"
  - "sdk/identity/identity/test/manual/*"
  - "sdk/cosmosdb/cosmos/samples/*"
  - eng/tools/versioning/*
language: js
root_check_enabled: True
required_readme_sections:
  - ^Azure (.+ client library for (JS|AMQP operations)|Smoke Test for JS)
  - ^Getting started$
  - ^Key concepts$
  - ^Examples$
  - ^Troubleshooting$
  - ^Next steps$
  - ^Contributing$
known_content_issues:
  - ["README.md", "#1583"]
  - ["sdk/template/template/README.md", "#1583"]
  - ["sdk/appconfiguration/app-configuration/README.md", "#1583"]
  - ["sdk/applicationinsights/applicationinsights-query/README.md", "#1583"]
  - ["sdk/batch/batch/README.md", "#1583"]
  - [
      "sdk/cognitiveservices/cognitiveservices-anomalydetector/README.md",
      "#1583",
    ]
  - ["sdk/cognitiveservices/cognitiveservices-autosuggest/README.md", "#1583"]
  - [
      "sdk/cognitiveservices/cognitiveservices-computervision/README.md",
      "#1583",
    ]
  - [
      "sdk/cognitiveservices/cognitiveservices-contentmoderator/README.md",
      "#1583",
    ]
  - [
      "sdk/cognitiveservices/cognitiveservices-customimagesearch/README.md",
      "#1583",
    ]
  - ["sdk/cognitiveservices/cognitiveservices-customsearch/README.md", "#1583"]
  - [
      "sdk/cognitiveservices/cognitiveservices-customvision-prediction/README.md",
      "#1583",
    ]
  - [
      "sdk/cognitiveservices/cognitiveservices-customvision-training/README.md",
      "#1583",
    ]
  - ["sdk/cognitiveservices/cognitiveservices-entitysearch/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-face/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-imagesearch/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-localsearch/README.md", "#1583"]
  - [
      "sdk/cognitiveservices/cognitiveservices-luis-authoring/README.md",
      "#1583",
    ]
  - ["sdk/cognitiveservices/cognitiveservices-luis-runtime/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-newssearch/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-qnamaker/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-spellcheck/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-textanalytics/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-videosearch/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-visualsearch/README.md", "#1583"]
  - ["sdk/cognitiveservices/cognitiveservices-websearch/README.md", "#1583"]
  - ["sdk/eventgrid/eventgrid/README.md", "#1583"]
  - ["sdk/core/abort-controller/README.md", "#1583"]
  - ["sdk/core/core-auth/README.md", "#1583"]
  - ["sdk/core/logger/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/test/readme.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/readme.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/UserManagement/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/TodoApp/readme.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/ChangeFeed/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/MultiRegionWrite/readme.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/ServerSideScripts/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/ServerSideScripts/JS/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/IndexManagement/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/ItemManagement/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/DatabaseManagement/README.md", "#1583"]
  - ["sdk/cosmosdb/cosmos/samples/ContainerManagement/README.md", "#1583"]
  - ["sdk/eventhub/README.md", "#1583"]
  - ["sdk/eventhub/event-hubs/README.md", "#1583"]
  - ["sdk/eventhub/eventhubs-checkpointstore-blob/README.md", "#1583"]
  - ["sdk/eventhub/event-hubs/samples/README.md", "#1583"]
  - ["sdk/eventhub/event-processor-host/README.md", "#1583"]
  - ["sdk/eventhub/event-processor-host/samples/README.md", "#1583"]
  - ["sdk/eventhub/testhub/README.md", "#1583"]
  - ["sdk/graphrbac/graph/README.md", "#1583"]
  - ["sdk/keyvault/keyvault/README.md", "#1583"]
  - ["sdk/operationalinsights/loganalytics/README.md", "#1583"]
  - ["sdk/servicebus/service-bus/README.md", "#1583"]
  - ["sdk/servicebus/service-bus/samples/README.md", "#1583"]
  - ["sdk/servicebus/service-bus/test/README.md", "#1583"]
  - ["sdk/servicefabric/servicefabric/README.md", "#1583"]
  - ["sdk/storage/README.md", "#1583"]
  - ["sdk/storage/storage-blob/README.md", "#1583"]
  - ["sdk/storage/storage-blob/swagger/README.md", "#1583"]
  - ["sdk/storage/storage-blob/samples/README.md", "#1583"]
  - ["sdk/storage/storage-blob/test/README.md", "#1583"]
  - ["sdk/storage/storage-file/README.md", "#1583"]
  - ["sdk/storage/storage-file/swagger/README.md", "#1583"]
  - ["sdk/storage/storage-file/samples/README.md", "#1583"]
  - ["sdk/storage/storage-file/test/README.md", "#1583"]
  - ["sdk/storage/storage-queue/README.md", "#1583"]
  - ["sdk/storage/storage-queue/swagger/README.md", "#1583"]
  - ["sdk/storage/storage-queue/samples/README.md", "#1583"]
  - ["sdk/storage/storage-queue/test/README.md", "#1583"]
  - ["sdk/storage/storage-datalake/README.md", "#1583"]
  - ["sdk/test-utils/recorder/README.md", "#1583"]
  - ["sdk/core/core-tracing/README.md", "#1583"]

package_indexing_exclusion_list:
  - "@azure/template"
  - "azure-sp"
  - "testhub"
  - "azure-sdk-for-js"
