parameters:
  nodeVersion: ''

jobs:
- job: 'testOn${{parameters.nodeVersion}}'
  pool:
    vmImage: 'Ubuntu 16.04'
  dependsOn: Pack
  condition: succeeded()
  steps:
  - script: 'sudo apt-get update'
    displayName: 'sudo apt-get update'
  - script: 'sudo apt install chromium-browser'
    displayName: 'sudo apt install chromium-browser'
  - task: NodeTool@0
    displayName: 'Install Node ${{parameters.nodeVersion}}'
    inputs:
      versionSpec: '${{parameters.nodeVersion}}.x'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: dist
      downloadPath: $(System.DefaultWorkingDirectory)
  - script: 'npm test'
