omitted_paths:
  - README.md
  - common/*
  - documentation/ServicePrincipal/*
  - eng/*
  - samples/*
  - sdk/*/README.md
  - sdk/**/samples-*/*
  - sdk/**/samples/*
  - sdk/**/swagger/*
  - sdk/**/test/**
  - sdk/*/arm-*
  - sdk/*/perf-tests/*
  - sdk/appconfiguration/app-configuration/sample-react/README.md
  - sdk/applicationinsights/applicationinsights-query/README.md
  - sdk/batch/batch/README.md
  - sdk/cognitiveservices/*
  - sdk/core/README.md
  - sdk/eventhub/event-processor-host/README.md
  - sdk/graphrbac/graph/README.md
  - sdk/operationalinsights/loganalytics/README.md
  - sdk/servicefabric/servicefabric/README.md
  - sdk/storage/storage-datalake/README.md
  - sdk/storage/storage-internal-avro/*
  - sdk/test-utils/perfstress/README.md
language: js
root_check_enabled: True
required_readme_sections:
  - ^Azure (.+ client library for (JavaScript|AMQP operations)|Smoke Test for JavaScript)
  - ^Getting started$
  - ^Key concepts$
  - ^Examples$
  - ^Troubleshooting$
  - ^Next steps$
  - ^Contributing$

known_content_issues:
  - ["sdk/core/abort-controller/README.md",  "#14714"]
  - ["sdk/core/core-amqp/README.md",  "#14715"]
  - ["sdk/core/core-auth/README.md",  "#14716"]
  - ["sdk/core/core-tracing/README.md",  "#14725"]
  - ["sdk/core/logger/README.md",  "#14726"]
  - ["sdk/eventhub/event-processor-host/README.md",  "#14727"]
  - ["sdk/eventhub/mock-hub/README.md",  "azure-sdk-tools/issues/1530"]
  - ["sdk/keyvault/keyvault-common/README.md",  "#15587"]
  - ["sdk/test-utils/multi-version/README.md", "#14728"]

package_indexing_exclusion_list:
  - "@azure/template"
  - "azure-sp"
  - "azure-sdk-for-js"
